spring.application.name=brobook


spring.datasource.url=jdbc:mysql://localhost:3306/brobook
spring.datasource.username=broBook
spring.datasource.password=broBookPW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
